<?php

$terms = array(
'hi' => array(
'seo_title' => 'फिंतरा - म्यूच्यूअल फंड्स और सिप',
'seo_description' => 'फिंतरा निवेश के बारें में ज्ञान पाने का एक नया और आधुनिक मंच है | फिंतरा ऐप  पर आप म्यूच्यूअल फंड्स, सिप , इक्विटी फंड्स,  elss , बीमा आदि के बारें में जानकारी  सरल भाषा में प्राप्त कर सकते हैं |',
'seo_keywords' => 'म्यूच्यूअल फंड्स, जानकारी , फिक्स्ड डिपाजिट , सिप , इक्विटी म्यूच्यूअल फण्ड , बीमा , बिटकॉइन , डेब्ट म्यूच्यूअल फण्ड , टैक्स सेविंग',

'title' => 'म्यूच्यूअल फंड्स में निवेश करने के बारें में सीखें.',
'description' => 'फिंतरा ऐप पर आप निवेश से सम्बंधित कोई भी जानकारी सरल एवं संक्षिप्त तरीके से जान सकते हैं | म्यूच्यूअल फंडस, सिप (SIP) , बीमा , बिटकॉइन  , टैक्स आदि से सम्बंधित जानकारी प्राप्त करने के लिए निचे दिए लिंक पर क्लिक करें और  ऐप इनस्टॉल करें  |'

),

'en' => array

(

'seo_title' => 'Fintra - Learn and Invest in Mutual Funds and SIP',
'seo_description' => 'Best Mutual Funds App in India. Download Fintra and invest in best mutual funds online. Your online mutual fund advisor and investment planner.',
'seo_keywords' => 'learn, education, finance, mutual funds, sip, insurance, wealth, money ,  systematic investment plan , equity funds , debt funds' ,
'title' => 'Learn and Invest in Mutual Funds, SIP or ELSS.',
'description' => 'Fintra mutual fund app is a leading investment app in India. Fintra simplifies the investment process through the use of state of art technology and expert financial guidance. Fintra helps you understand, research and inquire before you invest. We aim to become your trusted partner in the whole process of financial planning. Download our app now to start your financial journey with Fintra.Fintra can help you in complete financial planning, goal based investments, retirement planning or even generating monthly income.'
)
,

'gu' => array(
'seo_title' => 'Fintra - મ્યુચ્યુઅલ ફંડ્સ અને એસઆઈપીમાં જાણો અને રોકાણ કરો ',
'seo_description' => 'ભારતમાં શ્રેષ્ઠ મ્યુચ્યુઅલ ફંડ એપ્લિકેશન ફિન્ન્ટ્રા ડાઉનલોડ કરો અને ઓનલાઇન શ્રેષ્ઠ મ્યુચ્યુઅલ ફંડોમાં રોકાણ કરો. તમારી ઑનલાઇન મ્યુચ્યુઅલ ફંડ સલાહકાર અને રોકાણ આયોજક',
'seo_keywords' => '',
'title' =>'મ્યુચ્યુઅલ ફંડ્સ, SIP અથવા ELSS જાણો અને રોકાણ કરો',
'description'=>'ફિન્ન્ટ્રા મ્યુચ્યુઅલ ફંડ એપ્લિકેશન ભારતમાં એક અગ્રણી રોકાણ એપ્લિકેશન છે. ફિન્ન્ટા આર્ટ ટેક્નોલોજી અને નિષ્ણાત નાણાકીય માર્ગદર્શનના ઉપયોગ દ્વારા રોકાણ પ્રક્રિયાને સરળ બનાવે છે. ફિન્ન્ટ્રા તમે રોકાણ પહેલાં સમજી, સંશોધન અને પૂછપરછ માટે મદદ કરે છે. અમે નાણાકીય આયોજનની સમગ્ર પ્રક્રિયાની તમારા વિશ્વસનીય ભાગીદાર બનવાનું લક્ષ્ય રાખીએ છીએ. ફિન્ટ્રા સાથે તમારી નાણાકીય સફર શરૂ કરવા માટે હવે અમારી એપ્લિકેશન ડાઉનલોડ કરો. ફિન્ટ્રા સંપૂર્ણ નાણાકીય આયોજન, ધ્યેય આધારિત રોકાણ, નિવૃત્તિ આયોજન અથવા માસિક આવક પેદા કરવામાં તમારી સહાય કરી શકે છે.'

)
)


;

?>
