<?php
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
header('Access-Control-Max-Age: 1000');
header('Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With');
require_once 'utils/cmsutils.php';
DEFINE('SERVER_DNS' , 'https://fintra.co.in');
require_once 'utils/memcache.php';
class Utils{

	static $language_keys = array('english' => 'en' , 'hindi' => 'hi' , 'gujarati' => 'gu');
	static $language_keys_rev= array('en' => 'english' , 'hi' => 'hindi' , 'gu' => 'gujarati');
        static $jwt_secret_key = 'fintr@n3v3rshar3key';

	public static function parseParams(&$params){
		$body = $params['body-json'];
		$query_string = $params['params']['querystring'];
		$context = $params['context'];
		$new_params = array();

		$sourceIP = $context['source-ip'];
		$source_ua = $context['user-agent'];
		foreach($body  as $key=>$value){
			$new_params[$key] = $value;
		}
		foreach($query_string  as $key=>$value){
			$new_params[$key] = $value;
		}
		$new_params['sourceIP'] = $sourceIP;
		$new_params['user-agent'] = $source_ua;

		$params = $new_params;
	}

	public static function encodeJWT($user){
		$secret_key = Utils::$jwt_secret_key;
        	// base64 encodes the header json
        	$encoded_header = base64_encode('{"alg": "HS256","typ": "JWT"}');

        	$uid = $user['id'];
        	$ts = time();
        	// base64 encodes the payload json
        	$payload = array();
        	$payload['uid'] = $uid;
        	$payload['iat'] = $ts;
        	$payload_str = json_encode($payload);
        	$encoded_payload = base64_encode($payload_str);

        	// base64 strings are concatenated to one that looks like this
        	$header_payload = $encoded_header . '.' . $encoded_payload;

        	//Setting the secret key
        	$secret_key = 'fintr@n3v3rshar3key';

        	// Creating the signature, a hash with the s256 algorithm and the secret key. The signature is also base64 encoded.
        	$signature = base64_encode(hash_hmac('sha256', $header_payload, $secret_key, true));

        	// Creating the JWT token by concatenating the signature with the header and payload, that looks like this:
        	$jwt_token = $header_payload . '.' . $signature;

        	//listing the resulted  JWT
        	return $jwt_token;
	}

	public static function decodeJWT($recievedJwt){
		$secret_key = Utils::$jwt_secret_key;

        	// Split a string by '.' 
        	$jwt_values = explode('.', $recievedJwt);

        	// extracting the signature from the original JWT 
        	$recieved_signature = $jwt_values[2];

        	// concatenating the first two arguments of the $jwt_values array, representing the header and the payload
        	$recievedHeaderAndPayload = $jwt_values[0] . '.' . $jwt_values[1];

        	// creating the Base 64 encoded new signature generated by applying the HMAC method to the concatenated header and payload values
        	$resultedsignature = base64_encode(hash_hmac('sha256', $recievedHeaderAndPayload, $secret_key, true));

        	// checking if the created signature is equal to the received signature
        	if($resultedsignature == $recieved_signature) {
        	        return true;
        	}
        	return false;
	}


	public static function gen_uuid() {
 	   return sprintf( '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
        	// 32 bits for "time_low"
        	mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ),

        	// 16 bits for "time_mid"
        	mt_rand( 0, 0xffff ),

        	// 16 bits for "time_hi_and_version",
        	// four most significant bits holds version number 4
        	mt_rand( 0, 0x0fff ) | 0x4000,

        	// 16 bits, 8 bits for "clk_seq_hi_res",
        	// 8 bits for "clk_seq_low",
        	// two most significant bits holds zero and one for variant DCE1.1
        	mt_rand( 0, 0x3fff ) | 0x8000,

        	// 48 bits for "node"
        	mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff )
    		);
	}

	public static function getMenu($ln){
		$memcache_key = 'getMenu-' . $ln;
		$new_menus = MemcacheUtil::getItem($memcache_key);
		if(empty($new_menus)){
		$lang_key = isset(static::$language_keys[$ln]) ? static::$language_keys[$ln] : 'en' ;
		$menus = CMSUtils::getMenus(array('language' => $lang_key));
		$new_menus = array();
		foreach($menus as $key=>$menu){
			if($menu['is_translated'] == "1")
				$menu_url = '/'. $ln . '/' . $menu['url'];
			else
				$menu_url = '/' . $menu['url'];
			$menu_url = rtrim($menu_url , '/');
			$new_menus[] = array('id'=> $key, 'caption' => $menu['menu_name'] , 'href' => $menu_url);
		}
		MemcacheUtil::setItem($memcache_key , $new_menus);
		}
		return $new_menus;
	}


	public static function highlight($value , $key){
                $value =  $value ;
                $highlighted = $value;
                if (strpos($value,$key) !== FALSE){
                        $start_pos = strpos($value,$key);
                        $len = strlen($key);

                        $str1 = substr($value , 0 , $start_pos);
                        $str2 = substr($value , $start_pos , $len);
                        $str3 = substr($value , $start_pos + $len );

                        $highlighted = '<b>' .  $str1 . '</b>' . $str2  . '<b>' . $str3 . '</b>';
                }
                return $highlighted;
	}

	public function encrypt ($pure_string, $encryption_key) {
       	 	$cipher     = 'AES-256-CBC';
       	 	$options    = OPENSSL_RAW_DATA;
       	 	$hash_algo  = 'sha256';
       	 	$sha2len    = 32;
       	 	$ivlen = openssl_cipher_iv_length($cipher);
       	 	$iv = openssl_random_pseudo_bytes($ivlen);
       	 	//$ciphertext_raw = openssl_encrypt($pure_string, $cipher, $encryption_key, $options, $iv);
       	 	$ciphertext_raw = openssl_encrypt($pure_string, $cipher, $encryption_key);
       	 	//$hmac = hash_hmac($hash_algo, $ciphertext_raw, $encryption_key, true);
       	 	#return $iv.$hmac.$ciphertext_raw;
       	 	return $ciphertext_raw;
    	}
    	public function decrypt ($encrypted_string, $encryption_key) {
        	$cipher     = 'AES-256-CBC';
        	$options    = OPENSSL_RAW_DATA;
        	$hash_algo  = 'sha256';
        	$sha2len    = 32;
        	$ivlen = openssl_cipher_iv_length($cipher);
        	#$iv = substr($encrypted_string, 0, $ivlen);
        	#$hmac = substr($encrypted_string, $ivlen, $sha2len);
        	#$ciphertext_raw = substr($encrypted_string, $ivlen+$sha2len);
        	//$original_plaintext = openssl_decrypt($ciphertext_raw, $cipher, $encryption_key, $options, $iv);
        	$original_plaintext = openssl_decrypt($encrypted_string, $cipher, $encryption_key);
        	/*$calcmac = hash_hmac($hash_algo, $ciphertext_raw, $encryption_key, true);
        	if(function_exists('hash_equals')) {
        	    if (hash_equals($hmac, $calcmac)) return $original_plaintext;
        	} else {
        	    if ($this->hash_equals_custom($hmac, $calcmac)) return $original_plaintext;
        	}*/
		return $original_plaintext;
	}

	public function hash_equals_custom($knownString, $userString) {
        	if (function_exists('mb_strlen')) {
        	    $kLen = mb_strlen($knownString, '8bit');
        	    $uLen = mb_strlen($userString, '8bit');
        	} else {
        	    $kLen = strlen($knownString);
        	    $uLen = strlen($userString);
        	}
        	if ($kLen !== $uLen) {
        	    return false;
        	}
        	$result = 0;
        	for ($i = 0; $i < $kLen; $i++) {
        	    $result |= (ord($knownString[$i]) ^ ord($userString[$i]));
        	}
        	return 0 === $result;
    	}

	public function encodeURL($type , $id, $l){
		$base = 'https://fintra.co.in';
		$map = array('en' => 'english' , 'hi' => 'hindi');
		if(empty($l))
			$l = 'en';
		$l1 = $map[$l];
		return $base .'/' . $l1 . '/' . $type . '/' . $id;
	}


	public function decodeURL($url){

	}

	public static function read_time($text){
		return ceil(str_word_count($text)/256);

	}

	public static function translate($key , $lang){
		$file = '/var/www/html/conf/' . $lang . '.json';
		$json =  file_get_contents($file);
		$data = json_decode($json , true);
		
		if(is_array($key)){
			$resp =  array();
			foreach($key as $k){
				if(isset($data[$k]))
					$resp[] = $data[$k];
				else
					$resp[] = $k;
			}
			return $resp;
		}
		if(isset($data[$key]))
			return $data[$key];
		return $key;
	}

}

?>
